require("bytedance.plugins-setup")
require("bytedance.core.options")
require("bytedance.core.keymaps")
require("bytedance.core.colorscheme")
require("bytedance.plugins.nvim-tree")
require("bytedance.plugins.comment")
require("bytedance.plugins.lualine")
require("bytedance.plugins.telescope")
require("bytedance.plugins.nvim-cmp")
require("bytedance.plugins.lsp.mason")
require("bytedance.plugins.lsp.lspsaga")
require("bytedance.plugins.lsp.lspconfig")
require("bytedance.plugins.lsp.null-ls")
require("bytedance.plugins.autopairs")
require("bytedance.plugins.treesitter")
require("bytedance.plugins.gitsigns")

vim.cmd("language en_US")
